export const RESET_STATE = 'RESET_STATE';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_ERROR = 'SET_ERROR';
export const SET_LOGGED_IN = 'SET_LOGGED_IN';
export const ADD_USER_PLAYLISTS = 'ADD_USER_PLAYLISTS';
export const ADD_PLAYLIST_SONGS = 'ADD_PLAYLIST_SONGS';